"""Dashboard Studio definition builder (SPEC §3.2).

Deterministic harness code — the LLM proposes *that* a dashboard be made and
passes this definition through the gated write tool; it never free-hands the
JSON. Structure mirrors the definition verified live against Splunk 10.2.2
(.claude/session/artifacts/dashboard-studio-definition.json): three panels —
single value, line-over-time, table — each on its own ds.search, grid layout.

The panel SPL matches raw auth.log text and extracts fields inline with rex,
so it works without any field-extraction add-on once the sample data is
ingested (Phase 5).
"""

from __future__ import annotations

from .alert import AlertContext
from .investigate import Investigation

# Demo-friendly default window: the sample data is loaded shortly before the
# demo, and classic syslog timestamps carry no year, so a relative window is
# the robust choice over the alert's absolute ISO times.
_EARLIEST = "-24h@h"
_LATEST = "now"

_REX = (
    'rex "(?<action_raw>Failed|Accepted) password for (?<user>\\S+) '
    'from (?<src_ip>\\S+) port"'
)


def build_brute_force_dashboard(investigation: Investigation, alert: AlertContext) -> dict:
    """A 3-panel evidence dashboard for a brute-force alert investigation."""
    src_ip = alert.entities.get("src_ip", "*")
    user = alert.entities.get("user", "*")
    base = f'index={alert.index} "password"'
    window = {"earliest": _EARLIEST, "latest": _LATEST}

    return {
        "title": f"SOC Assist — {alert.rule_name}",
        "description": (
            f"Evidence for {alert.rule_id} (fired {alert.fired_at}; "
            f"severity {investigation.severity}). Generated by soc-assist "
            "with human approval."
        ),
        "dataSources": {
            "ds_failed_count": {
                "type": "ds.search",
                "name": "Total failed attempts",
                "options": {
                    "query": (
                        f'index={alert.index} "Failed password" | {_REX} '
                        f'| search src_ip="{src_ip}" user="{user}" '
                        "| stats count"
                    ),
                    "queryParameters": window,
                },
            },
            "ds_failures_over_time": {
                "type": "ds.search",
                "name": "Failures over time",
                "options": {
                    "query": (
                        f'{base} "Failed password" | {_REX} '
                        f'| search src_ip="{src_ip}" '
                        "| timechart span=1m count as failures"
                    ),
                    "queryParameters": window,
                },
            },
            "ds_top_pairs": {
                "type": "ds.search",
                "name": "Sources and targeted users",
                "options": {
                    "query": (
                        f"{base} | {_REX} "
                        '| stats count(eval(action_raw="Failed")) as failures, '
                        'count(eval(action_raw="Accepted")) as successes '
                        "by src_ip, user | sort - failures"
                    ),
                    "queryParameters": window,
                },
            },
        },
        "visualizations": {
            "viz_failed_count": {
                "type": "splunk.singlevalue",
                "title": f"Failed logins: {user} from {src_ip}",
                "dataSources": {"primary": "ds_failed_count"},
            },
            "viz_failures_over_time": {
                "type": "splunk.line",
                "title": "Failed logins over time (1m bins)",
                "dataSources": {"primary": "ds_failures_over_time"},
            },
            "viz_top_pairs": {
                "type": "splunk.table",
                "title": "Failures and successes by source IP and user",
                "dataSources": {"primary": "ds_top_pairs"},
            },
        },
        "layout": {
            "type": "grid",
            "options": {},
            "structure": [
                {"item": "viz_failed_count", "type": "block",
                 "position": {"x": 0, "y": 0, "w": 400, "h": 300}},
                {"item": "viz_failures_over_time", "type": "block",
                 "position": {"x": 400, "y": 0, "w": 800, "h": 300}},
                {"item": "viz_top_pairs", "type": "block",
                 "position": {"x": 0, "y": 300, "w": 1200, "h": 400}},
            ],
        },
        "defaults": {
            "dataSources": {"ds.search": {"options": {"queryParameters": window}}}
        },
    }
